apiVersion: v1
kind: PersistentVolume
metadata:
 name: wordpress-pv1
 labels:
    failure-domain.beta.kubernetes.io/region: us-south
    failure-domain.beta.kubernetes.io/zone: dal13
spec:
 storageClassName: ""
 capacity:
   storage: "20Gi"
 accessModes:
   - ReadWriteMany
 nfs:
   server: "fsm-dal1301b-fz.adn.networklayer.com"
   path: "/SL02SEV1801519_1/data01"
